## ASSIGNMENT 1(Numpy_Pandas)

In [9]:
# Exercise 1:  Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. 
import numpy as np
arr1 = np.arange(1,11)
arr2 = arr1.reshape(2,5)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
#Exercise 2: Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 
arr = np.arange(1,21)
print(arr[5:15])

[ 6  7  8  9 10 11 12 13 14 15]


In [13]:
"""
Exercise 3: Create a Pandas series with the following data: 
{'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.
"""
import pandas as pd
series = pd.Series({'apples' : 3,'bananas' : 2, 'oranges' : 1})
print(series)
series['pears'] = 4
print(series)

apples     3
bananas    2
oranges    1
dtype: int64
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [15]:
#Exercise 4: Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
data = {'Name':['Manu','Anu','Kris','Lina','James','Minu','Sam','Jolly','Anna','Moly'], 'Age':[28,24,35,32,40,34,23,43,21,45],
        'Gender' : ['M','F','M','F','M','F','M','F','F','F']}
df = pd.DataFrame(data)
print(df)

    Name  Age Gender
0   Manu   28      M
1    Anu   24      F
2   Kris   35      M
3   Lina   32      F
4  James   40      M
5   Minu   34      F
6    Sam   23      M
7  Jolly   43      F
8   Anna   21      F
9   Moly   45      F


In [17]:
"""
Exercise 5: Add a new column to the data frame created in question 1, called occupation. 
The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.
"""
df['Occupation'] = ['Programmer','Analyst','Manager','Programmer','Analyst','Manager','Programmer','Analyst','Manager','Programmer']
print(df)

    Name  Age Gender  Occupation
0   Manu   28      M  Programmer
1    Anu   24      F     Analyst
2   Kris   35      M     Manager
3   Lina   32      F  Programmer
4  James   40      M     Analyst
5   Minu   34      F     Manager
6    Sam   23      M  Programmer
7  Jolly   43      F     Analyst
8   Anna   21      F     Manager
9   Moly   45      F  Programmer


In [25]:
##Exercise 6: Select the rows of the dataframe where the age is greater than or equal to 30. 
print(df[df['Age'] >= 30])

    Name  Age Gender  Occupation
2   Kris   35      M     Manager
3   Lina   32      F  Programmer
4  James   40      M     Analyst
5   Minu   34      F     Manager
7  Jolly   43      F     Analyst
9   Moly   45      F  Programmer


In [23]:
#Exercise 7: Convert this dataframe to a csv file and read that csv file, finally display the contents.
df.to_csv('data.csv' , index=False)
df_read = pd.read_csv('data.csv')
print(df_read)

    Name  Age Gender  Occupation
0   Manu   28      M  Programmer
1    Anu   24      F     Analyst
2   Kris   35      M     Manager
3   Lina   32      F  Programmer
4  James   40      M     Analyst
5   Minu   34      F     Manager
6    Sam   23      M  Programmer
7  Jolly   43      F     Analyst
8   Anna   21      F     Manager
9   Moly   45      F  Programmer
